apriltag_node:
  ros__parameters:
    image_transport: "compressed"     # สำคัญ! ต้อง compressed กับ ZED เท่านั้น

    tag_families: "tag36h11"          # หรือใส่เป็น list ได้ ["tag36h11", "tag25h9"]
    publish_tf: true
    
    detector:
      threads: 2
      decimate: 1.0                   # 1.0 = แม่นยำสูงสุด (เปลี่ยนเป็น 2.0 ถ้า CPU ร้อน)
      blur: 0.0
      refine: true
      refine_edges: true
      decode_sharpening: 0.25

    tag:
      ids: [1, 2, 3, 4, 5, 6, 7, 8, 9, 11]
      sizes: [0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.04, 0.10]
      frames: ["tag1", "tag2", "tag3", "tag4", "tag5", "tag6", "tag7", "tag8", "tag9", "tag11"]